# Generated by Django 5.2.1 on 2025-05-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ATLAS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compound',
            name='formula',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='compound',
            name='inchi',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='compound',
            name='smiles',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
