name: Docker Image CI

on:
  push:
    branches: [ "develop" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and deploy the Google App Engine web app
      run: docker-compose -f docker-compose-deploy.yml run --rm --remove-orphans gcloud gcloud app deploy --project atlas-demo-459504
